### ISSUE TITLE
Include image examples in the last three tabs.

### ISSUE THREAD

**Issue by BrennanCuppage** [kellenceriani/kellenceriani.github.io#1]
Your AR/Unity Games tab, art/interactive comic tab, and webdesign tab should have pictures in addition to, or instead of, the plain hyperlinks to the google drive. Screenshots will help your examples pop and give a preview of the contents of the link.

**Comment by kellenceriani** [comment]
Added videos to showcase AR/Unity Games tab, art/interactive comic tab, and webdesign tab. Changed entire landscape of the website to give a more appealing preview for user.
