### ISSUE TITLE
Initial Look

### ISSUE THREAD

**Issue by markkanthonyf** [kellenceriani/kellenceriani.github.io#2]
The first thing I would suggest is changing the home page just a bit. Your picture is good, but I would suggest putting your social media, and more of your "about" kind of things on a different page. Make the first thing someone sees attention grabbing. Like your most proudest work, your most detailed project, or something along those lines. I believe this will help people's interests, especially employers, when looking at your website. That way once they're greeted with something your proud of, it'll be because of their interest and intrique that they keep going through your website. It'll be because of their intrique that they look for your social medias/about page. 

Not that having your about page as the first thing a person sees isn't bad, but I don't believe it will push an employer to continue looking at your website, y'know?

**Comment by kellenceriani** [comment]
Changed the home page (drastically lol).  I added a parallax scrolling with some artwork. The home page is still my About page but I may end up changing that as well.
